# Generated by Django 3.2.7 on 2024-01-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_price_buy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='average_price',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=20, verbose_name='Μεση Τιμή'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_buy',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=20, verbose_name='Τελευταία Τιμή Αγοράς'),
        ),
        migrations.AlterField(
            model_name='product',
            name='running_average_price',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=20, verbose_name='Τρέχων Μεση Τιμή'),
        ),
    ]
