# Generated by Django 3.2.7 on 2024-01-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20240116_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_buy',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=20, verbose_name='Τελευταία Τιμή Αγοράς'),
        ),
    ]
