# Generated by Django 3.2.7 on 2024-01-18 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_price_buy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricelistitem',
            name='product',
        ),
        migrations.AddField(
            model_name='pricelistitem',
            name='title',
            field=models.CharField(max_length=220, null=True),
        ),
    ]
