# Generated by Django 3.2.7 on 2024-01-18 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20240118_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='folder',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, null=True, verbose_name='ΑΔΕΙΟΔΟΤΗΣΗ'),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='install_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='ΑΜΟΙΒΗ ΕΓΚΑΤΑΣΤΑΣΗΣ'),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='margin',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, null=True, verbose_name='ΣΥΝΟΛΟ'),
        ),
        migrations.AddField(
            model_name='pricelistitem',
            name='discount_percent',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=20, verbose_name='ΕΚΠΤΩΣΗ ΠΟΣΟΣΤΟ'),
        ),
        migrations.AddField(
            model_name='pricelistitem',
            name='final_value_margin',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=20, verbose_name='ΑΞΙΑ ΠΩΛΗΣΗΣ'),
        ),
        migrations.AddField(
            model_name='pricelistitem',
            name='final_value_unit',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=20, verbose_name='ΤΕΛΙΚΗ ΤΙΜΗ ΜΟΝΑΔΑΣ'),
        ),
        migrations.AddField(
            model_name='pricelistitem',
            name='margin',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=20, verbose_name='ΠΟΣΟΣΤΟ ΚΕΡΔΟΥΣ'),
        ),
        migrations.AddField(
            model_name='pricelistitem',
            name='unit',
            field=models.CharField(choices=[('a', 'Τεμάχιο'), ('b', 'Κιβώτιο'), ('c', 'Κιλό'), ('d', 'Μέτρα')], default='a', max_length=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('a', 'Τεμάχιο'), ('b', 'Κιβώτιο'), ('c', 'Κιλό'), ('d', 'Μέτρα')], default='a', max_length=1),
        ),
        migrations.CreateModel(
            name='CategoryPriceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220, unique=True)),
                ('is_parent', models.BooleanField(default=False)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='childrens', to='products.categorypricelist')),
            ],
        ),
        migrations.AddField(
            model_name='pricelistitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.categorypricelist'),
        ),
    ]
