# Generated by Django 3.2.7 on 2024-01-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20240118_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelist',
            name='clean_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, null=True, verbose_name='ΑΞΙΑ ΠΡΟΪΟΝΤΩΝ'),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='taxes_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, null=True, verbose_name='ΦΠΑ'),
        ),
        migrations.AddField(
            model_name='pricelistitem',
            name='taxes_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ΠΟΣΟΤΗΤΑ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='ΚΑΘΑΡΗ'),
        ),
    ]
