# Generated by Django 3.2.7 on 2024-01-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20240118_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricelistitem',
            name='taxes_modifier',
            field=models.IntegerField(default=24),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='margin',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5, verbose_name='ΠΟΣΟΣΤΟ ΚΕΡΔΟΥΣ'),
        ),
    ]
