# Generated by Django 3.2.7 on 2024-01-18 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20240118_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorypricelist',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='childrens', to='products.categorypricelist'),
        ),
        migrations.AlterField(
            model_name='pricelistitem',
            name='taxes_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ΠΟΣΟΤΗΤΑ'),
        ),
        migrations.AlterField(
            model_name='pricelistitem',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pricelistitem',
            name='unit',
            field=models.CharField(choices=[('a', 'Τμχ'), ('b', 'Κιβώτιο'), ('c', 'Kg'), ('d', 'm')], default='a', max_length=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('a', 'Τμχ'), ('b', 'Κιβώτιο'), ('c', 'Kg'), ('d', 'm')], default='a', max_length=1),
        ),
    ]
