# Generated by Django 3.2.7 on 2024-01-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20240118_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelistitem',
            name='margin',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='ΠΟΣΟΣΤΟ ΚΕΡΔΟΥΣ'),
        ),
    ]
