# Generated by Django 3.2.7 on 2024-01-18 10:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0011_alter_paymentinvoice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinvoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 18, 10, 4, 51, 44297, tzinfo=utc), verbose_name='ΗΜΕΡΟΜΗΝΙΑ'),
        ),
    ]
