# Generated by Django 3.2.7 on 2024-01-18 11:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0012_alter_paymentinvoice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='unit',
            field=models.CharField(choices=[('a', 'Τμχ'), ('b', 'Κιβώτιο'), ('c', 'Kg'), ('d', 'm')], default='a', max_length=1, verbose_name='ΜΜ'),
        ),
        migrations.AlterField(
            model_name='paymentinvoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 18, 11, 32, 4, 115073, tzinfo=utc), verbose_name='ΗΜΕΡΟΜΗΝΙΑ'),
        ),
    ]
