# Generated by Django 3.2.7 on 2023-12-11 07:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0008_alter_paymentinvoice_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='costumer',
            name='city',
            field=models.CharField(blank=True, max_length=220, null=True, verbose_name='πολη'),
        ),
        migrations.AlterField(
            model_name='paymentinvoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 11, 7, 59, 12, 490575, tzinfo=utc), verbose_name='ΗΜΕΡΟΜΗΝΙΑ'),
        ),
    ]
