# Generated by Django 3.2.7 on 2023-12-11 08:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0009_auto_20231211_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinvoice',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 11, 8, 16, 39, 360561, tzinfo=utc), verbose_name='ΗΜΕΡΟΜΗΝΙΑ'),
        ),
    ]
