# Generated by Django 3.2.7 on 2024-01-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='initial_years_filter',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
