# Generated by Django 3.2.7 on 2024-01-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='income_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='ΠΟΣΟΣΤΟ ΚΕΡΔΟΥΣ'),
        ),
    ]
