# Generated by Django 3.2.7 on 2024-01-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_alter_invoiceitem_income_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='clean_value',
            field=models.DecimalField(decimal_places=5, max_digits=17, verbose_name='Αξια'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='discount_value',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10, verbose_name='Ποσο Εκπτωσης'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='final_value_unit',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=17, verbose_name='Τελικη Αξία'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='qty',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=17, verbose_name='Ποσότητα'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='taxes_value',
            field=models.DecimalField(decimal_places=5, max_digits=17, verbose_name='Αξια ΦΠΑ'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='total_clean_value',
            field=models.DecimalField(decimal_places=5, max_digits=17, verbose_name='Καθαρη Αξια'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='total_value',
            field=models.DecimalField(decimal_places=5, max_digits=17, verbose_name='Τελικη Αξία'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='value',
            field=models.DecimalField(decimal_places=5, max_digits=17, verbose_name='Τιμή Μοναδας'),
        ),
    ]
