# Generated by Django 3.2.7 on 2024-01-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_auto_20240112_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='extra_value',
            field=models.DecimalField(decimal_places=4, max_digits=20, verbose_name='ΜΕΤΑΦΟΡΙΚΑ'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='final_value',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=20, verbose_name='Αξία'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='value',
            field=models.DecimalField(decimal_places=4, max_digits=20, verbose_name='Καθαρή Αξια'),
        ),
    ]
