# Generated by Django 3.2.7 on 2024-01-18 05:50

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_auto_20240116_1136'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='invoiceitem',
            managers=[
                ('my_query', django.db.models.manager.Manager()),
            ],
        ),
    ]
