# Generated by Django 3.2.7 on 2024-01-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_alter_invoiceitem_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='unit',
            field=models.CharField(choices=[('a', 'Τεμάχιο'), ('b', 'Κιβώτιο'), ('c', 'Κιλό'), ('d', 'Μέτρα')], default='a', max_length=1, verbose_name='ΜΜ'),
        ),
    ]
