# Generated by Django 3.2.7 on 2024-01-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0007_alter_invoiceitem_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='unit',
            field=models.CharField(choices=[('a', 'Τμχ'), ('b', 'Κιβώτιο'), ('c', 'Kg'), ('d', 'm')], default='a', max_length=1, verbose_name='ΜΜ'),
        ),
    ]
