# Generated by Django 3.2.7 on 2023-12-11 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_auto_20231128_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='extra_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Αξια Μεταφορικων'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='clean_value',
            field=models.DecimalField(decimal_places=2, max_digits=17, verbose_name='Αξια'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ποσο Εκπτωσης'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='total_clean_value',
            field=models.DecimalField(decimal_places=2, max_digits=17, verbose_name='Καθαρη Αξια'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=17, verbose_name='Τιμή'),
        ),
    ]
