# Generated by Django 3.2.7 on 2023-12-11 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_auto_20231211_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='final_value_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Τελικη Αξία'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=17, verbose_name='Τιμή Μοναδας'),
        ),
    ]
